import { prisma } from "./index";

const questionsData = [
  {
    enonce: "Quelle balise est utilisée pour créer un lien hypertexte ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<a>", estCorrecte: true },
      { libelle: "<link>", estCorrecte: false },
      { libelle: "<href>", estCorrecte: false },
      { libelle: "<nav>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'insérer une image ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<img>", estCorrecte: true },
      { libelle: "<image>", estCorrecte: false },
      { libelle: "<picture>", estCorrecte: false },
      { libelle: "<src>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise contient les métadonnées ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<head>", estCorrecte: true },
      { libelle: "<meta>", estCorrecte: false },
      { libelle: "<header>", estCorrecte: false },
      { libelle: "<body>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit un paragraphe ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<p>", estCorrecte: true },
      { libelle: "<para>", estCorrecte: false },
      { libelle: "<text>", estCorrecte: false },
      { libelle: "<span>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise crée une liste non ordonnée ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<ul>", estCorrecte: true },
      { libelle: "<ol>", estCorrecte: false },
      { libelle: "<li>", estCorrecte: false },
      { libelle: "<list>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise crée une liste ordonnée ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<ol>", estCorrecte: true },
      { libelle: "<ul>", estCorrecte: false },
      { libelle: "<li>", estCorrecte: false },
      { libelle: "<order>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente le contenu principal ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<main>", estCorrecte: true },
      { libelle: "<section>", estCorrecte: false },
      { libelle: "<article>", estCorrecte: false },
      { libelle: "<div>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut rend un champ obligatoire ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "required", estCorrecte: true },
      { libelle: "validate", estCorrecte: false },
      { libelle: "mandatory", estCorrecte: false },
      { libelle: "checked", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut définit un texte alternatif pour une image ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "alt", estCorrecte: true },
      { libelle: "title", estCorrecte: false },
      { libelle: "src", estCorrecte: false },
      { libelle: "name", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'insérer une vidéo ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<video>", estCorrecte: true },
      { libelle: "<media>", estCorrecte: false },
      { libelle: "<movie>", estCorrecte: false },
      { libelle: "<mp4>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit le titre principal ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<h1>", estCorrecte: true },
      { libelle: "<title>", estCorrecte: false },
      { libelle: "<header>", estCorrecte: false },
      { libelle: "<head>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet un retour à la ligne ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<br>", estCorrecte: true },
      { libelle: "<newline>", estCorrecte: false },
      { libelle: "<lb>", estCorrecte: false },
      { libelle: "<break>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise crée un formulaire ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<form>", estCorrecte: true },
      { libelle: "<input>", estCorrecte: false },
      { libelle: "<button>", estCorrecte: false },
      { libelle: "<submit>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut définit l'adresse d'un lien ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "href", estCorrecte: true },
      { libelle: "src", estCorrecte: false },
      { libelle: "link", estCorrecte: false },
      { libelle: "url", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de créer un bouton ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<button>", estCorrecte: true },
      { libelle: "<click>", estCorrecte: false },
      { libelle: "<btn>", estCorrecte: false },
      { libelle: "<input>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise contient le contenu visible d'une page ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<body>", estCorrecte: true },
      { libelle: "<head>", estCorrecte: false },
      { libelle: "<html>", estCorrecte: false },
      { libelle: "<meta>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'afficher du texte en italique ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<i>", estCorrecte: true },
      { libelle: "<italic>", estCorrecte: false },
      { libelle: "<emphasis>", estCorrecte: false },
      { libelle: "<text>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'afficher du texte souligné ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<u>", estCorrecte: true },
      { libelle: "<underline>", estCorrecte: false },
      { libelle: "<line>", estCorrecte: false },
      { libelle: "<style>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente un élément de liste ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<li>", estCorrecte: true },
      { libelle: "<ul>", estCorrecte: false },
      { libelle: "<ol>", estCorrecte: false },
      { libelle: "<list>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'ajouter une ligne horizontale ?",
    categorie: "html",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<hr>", estCorrecte: true },
      { libelle: "<line>", estCorrecte: false },
      { libelle: "<border>", estCorrecte: false },
      { libelle: "<break>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente une section de contenu ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<section>", estCorrecte: true },
      { libelle: "<part>", estCorrecte: false },
      { libelle: "<content>", estCorrecte: false },
      { libelle: "<div>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente un article indépendant ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<article>", estCorrecte: true },
      { libelle: "<post>", estCorrecte: false },
      { libelle: "<block>", estCorrecte: false },
      { libelle: "<content>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente un menu de navigation ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<nav>", estCorrecte: true },
      { libelle: "<menu>", estCorrecte: false },
      { libelle: "<navbar>", estCorrecte: false },
      { libelle: "<navigate>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente le pied de page ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<footer>", estCorrecte: true },
      { libelle: "<bottom>", estCorrecte: false },
      { libelle: "<end>", estCorrecte: false },
      { libelle: "<base>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente l'en-tête d'une page ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<header>", estCorrecte: true },
      { libelle: "<top>", estCorrecte: false },
      { libelle: "<banner>", estCorrecte: false },
      { libelle: "<head>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut permet d'ouvrir un lien dans un nouvel onglet ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "target=\"_blank\"", estCorrecte: true },
      { libelle: "newtab", estCorrecte: false },
      { libelle: "blank", estCorrecte: false },
      { libelle: "open", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'intégrer du JavaScript ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<script>", estCorrecte: true },
      { libelle: "<javascript>", estCorrecte: false },
      { libelle: "<code>", estCorrecte: false },
      { libelle: "<js>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut définit la source d'une image ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "src", estCorrecte: true },
      { libelle: "href", estCorrecte: false },
      { libelle: "link", estCorrecte: false },
      { libelle: "path", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de lier une feuille CSS ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<link>", estCorrecte: true },
      { libelle: "<style>", estCorrecte: false },
      { libelle: "<css>", estCorrecte: false },
      { libelle: "<design>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'écrire du CSS interne ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<style>", estCorrecte: true },
      { libelle: "<css>", estCorrecte: false },
      { libelle: "<layout>", estCorrecte: false },
      { libelle: "<design>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise HTML5 permet d'intégrer du son ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<audio>", estCorrecte: true },
      { libelle: "<sound>", estCorrecte: false },
      { libelle: "<music>", estCorrecte: false },
      { libelle: "<mp3>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de dessiner des graphiques ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<canvas>", estCorrecte: true },
      { libelle: "<draw>", estCorrecte: false },
      { libelle: "<paint>", estCorrecte: false },
      { libelle: "<graphic>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'intégrer une page web externe ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<iframe>", estCorrecte: true },
      { libelle: "<frame>", estCorrecte: false },
      { libelle: "<embed>", estCorrecte: false },
      { libelle: "<object>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut définit un identifiant unique ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "id", estCorrecte: true },
      { libelle: "class", estCorrecte: false },
      { libelle: "name", estCorrecte: false },
      { libelle: "key", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut permet de définir plusieurs éléments avec le même style ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "class", estCorrecte: true },
      { libelle: "id", estCorrecte: false },
      { libelle: "style", estCorrecte: false },
      { libelle: "group", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit un tableau HTML ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<table>", estCorrecte: true },
      { libelle: "<tab>", estCorrecte: false },
      { libelle: "<grid>", estCorrecte: false },
      { libelle: "<data>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une ligne de tableau ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<tr>", estCorrecte: true },
      { libelle: "<td>", estCorrecte: false },
      { libelle: "<row>", estCorrecte: false },
      { libelle: "<line>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une cellule de tableau ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<td>", estCorrecte: true },
      { libelle: "<tr>", estCorrecte: false },
      { libelle: "<th>", estCorrecte: false },
      { libelle: "<cell>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une cellule d'en-tête dans un tableau ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<th>", estCorrecte: true },
      { libelle: "<td>", estCorrecte: false },
      { libelle: "<head>", estCorrecte: false },
      { libelle: "<title>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise regroupe l'en-tête d'un tableau ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<thead>", estCorrecte: true },
      { libelle: "<top>", estCorrecte: false },
      { libelle: "<header>", estCorrecte: false },
      { libelle: "<head>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise regroupe le corps d'un tableau ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<tbody>", estCorrecte: true },
      { libelle: "<body>", estCorrecte: false },
      { libelle: "<content>", estCorrecte: false },
      { libelle: "<tablebody>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise regroupe le pied d'un tableau ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<tfoot>", estCorrecte: true },
      { libelle: "<bottom>", estCorrecte: false },
      { libelle: "<foot>", estCorrecte: false },
      { libelle: "<end>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'intégrer du contenu externe comme un PDF ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<embed>", estCorrecte: true },
      { libelle: "<frame>", estCorrecte: false },
      { libelle: "<insert>", estCorrecte: false },
      { libelle: "<external>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'intégrer un objet externe ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<object>", estCorrecte: true },
      { libelle: "<external>", estCorrecte: false },
      { libelle: "<frame>", estCorrecte: false },
      { libelle: "<plugin>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une légende pour une image ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<figcaption>", estCorrecte: true },
      { libelle: "<caption>", estCorrecte: false },
      { libelle: "<legend>", estCorrecte: false },
      { libelle: "<description>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise regroupe une image et sa légende ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<figure>", estCorrecte: true },
      { libelle: "<imagegroup>", estCorrecte: false },
      { libelle: "<fig>", estCorrecte: false },
      { libelle: "<media>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit des données de machine lisibles ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<data>", estCorrecte: true },
      { libelle: "<info>", estCorrecte: false },
      { libelle: "<value>", estCorrecte: false },
      { libelle: "<meta>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une barre de progression ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<progress>", estCorrecte: true },
      { libelle: "<loading>", estCorrecte: false },
      { libelle: "<bar>", estCorrecte: false },
      { libelle: "<meter>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une mesure dans une plage ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<meter>", estCorrecte: true },
      { libelle: "<range>", estCorrecte: false },
      { libelle: "<progress>", estCorrecte: false },
      { libelle: "<value>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de regrouper des options dans un formulaire ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<fieldset>", estCorrecte: true },
      { libelle: "<group>", estCorrecte: false },
      { libelle: "<formgroup>", estCorrecte: false },
      { libelle: "<section>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de créer une zone de groupe dans un formulaire ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<fieldset>", estCorrecte: true },
      { libelle: "<group>", estCorrecte: false },
      { libelle: "<formgroup>", estCorrecte: false },
      { libelle: "<section>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit un titre pour un fieldset ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<legend>", estCorrecte: true },
      { libelle: "<title>", estCorrecte: false },
      { libelle: "<caption>", estCorrecte: false },
      { libelle: "<label>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de créer une zone de texte multi-ligne ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<textarea>", estCorrecte: true },
      { libelle: "<textinput>", estCorrecte: false },
      { libelle: "<inputtext>", estCorrecte: false },
      { libelle: "<textbox>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de créer une liste déroulante ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<select>", estCorrecte: true },
      { libelle: "<dropdown>", estCorrecte: false },
      { libelle: "<list>", estCorrecte: false },
      { libelle: "<optionlist>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une option dans une liste déroulante ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<option>", estCorrecte: true },
      { libelle: "<item>", estCorrecte: false },
      { libelle: "<choice>", estCorrecte: false },
      { libelle: "<selectitem>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut définit un texte indicatif dans un champ ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "placeholder", estCorrecte: true },
      { libelle: "hint", estCorrecte: false },
      { libelle: "text", estCorrecte: false },
      { libelle: "label", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut désactive un champ de formulaire ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "disabled", estCorrecte: true },
      { libelle: "inactive", estCorrecte: false },
      { libelle: "readonly", estCorrecte: false },
      { libelle: "off", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut rend un champ en lecture seule ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "readonly", estCorrecte: true },
      { libelle: "disabled", estCorrecte: false },
      { libelle: "static", estCorrecte: false },
      { libelle: "lock", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut permet d'indiquer plusieurs valeurs dans un champ fichier ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "multiple", estCorrecte: true },
      { libelle: "multi", estCorrecte: false },
      { libelle: "many", estCorrecte: false },
      { libelle: "files", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'associer un texte à un champ de formulaire ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<label>", estCorrecte: true },
      { libelle: "<caption>", estCorrecte: false },
      { libelle: "<name>", estCorrecte: false },
      { libelle: "<text>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut associe un label à un champ ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "for", estCorrecte: true },
      { libelle: "target", estCorrecte: false },
      { libelle: "id", estCorrecte: false },
      { libelle: "name", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut définit une valeur par défaut dans un champ ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "value", estCorrecte: true },
      { libelle: "default", estCorrecte: false },
      { libelle: "text", estCorrecte: false },
      { libelle: "init", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'intégrer une carte interactive HTML ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<map>", estCorrecte: true },
      { libelle: "<location>", estCorrecte: false },
      { libelle: "<geo>", estCorrecte: false },
      { libelle: "<area>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une zone cliquable dans une image map ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<area>", estCorrecte: true },
      { libelle: "<zone>", estCorrecte: false },
      { libelle: "<mapitem>", estCorrecte: false },
      { libelle: "<click>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit le titre d'une page HTML ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<title>", estCorrecte: true },
      { libelle: "<headtitle>", estCorrecte: false },
      { libelle: "<caption>", estCorrecte: false },
      { libelle: "<heading>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut indique la langue d'une page ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "lang", estCorrecte: true },
      { libelle: "language", estCorrecte: false },
      { libelle: "locale", estCorrecte: false },
      { libelle: "country", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une description pour les moteurs de recherche ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<meta>", estCorrecte: true },
      { libelle: "<description>", estCorrecte: false },
      { libelle: "<info>", estCorrecte: false },
      { libelle: "<seo>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel attribut définit l'encodage des caractères ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "charset", estCorrecte: true },
      { libelle: "encoding", estCorrecte: false },
      { libelle: "utf", estCorrecte: false },
      { libelle: "char", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de définir une citation longue ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<blockquote>", estCorrecte: true },
      { libelle: "<quote>", estCorrecte: false },
      { libelle: "<citation>", estCorrecte: false },
      { libelle: "<cite>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une citation courte ?",
    categorie: "html",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "<q>", estCorrecte: true },
      { libelle: "<quote>", estCorrecte: false },
      { libelle: "<cite>", estCorrecte: false },
      { libelle: "<shortquote>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de définir une liste de définitions ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<dl>", estCorrecte: true },
      { libelle: "<def>", estCorrecte: false },
      { libelle: "<definition>", estCorrecte: false },
      { libelle: "<listdef>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente un terme dans une liste de définitions ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<dt>", estCorrecte: true },
      { libelle: "<dd>", estCorrecte: false },
      { libelle: "<term>", estCorrecte: false },
      { libelle: "<def>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente la description d'un terme ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<dd>", estCorrecte: true },
      { libelle: "<desc>", estCorrecte: false },
      { libelle: "<definition>", estCorrecte: false },
      { libelle: "<text>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'afficher du texte préformaté ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<pre>", estCorrecte: true },
      { libelle: "<codeblock>", estCorrecte: false },
      { libelle: "<format>", estCorrecte: false },
      { libelle: "<raw>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente un fragment de code ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<code>", estCorrecte: true },
      { libelle: "<script>", estCorrecte: false },
      { libelle: "<program>", estCorrecte: false },
      { libelle: "<syntax>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente une variable ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<var>", estCorrecte: true },
      { libelle: "<variable>", estCorrecte: false },
      { libelle: "<value>", estCorrecte: false },
      { libelle: "<v>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente une entrée clavier ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<kbd>", estCorrecte: true },
      { libelle: "<key>", estCorrecte: false },
      { libelle: "<keyboard>", estCorrecte: false },
      { libelle: "<inputkey>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente une sortie de programme ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<samp>", estCorrecte: true },
      { libelle: "<output>", estCorrecte: false },
      { libelle: "<result>", estCorrecte: false },
      { libelle: "<display>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit un résultat calculé ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<output>", estCorrecte: true },
      { libelle: "<result>", estCorrecte: false },
      { libelle: "<calc>", estCorrecte: false },
      { libelle: "<answer>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente une date ou heure lisible par machine ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<time>", estCorrecte: true },
      { libelle: "<date>", estCorrecte: false },
      { libelle: "<clock>", estCorrecte: false },
      { libelle: "<datetime>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de définir une source pour un média ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<source>", estCorrecte: true },
      { libelle: "<media>", estCorrecte: false },
      { libelle: "<file>", estCorrecte: false },
      { libelle: "<stream>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de fournir des pistes de sous-titres ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<track>", estCorrecte: true },
      { libelle: "<subtitle>", estCorrecte: false },
      { libelle: "<caption>", estCorrecte: false },
      { libelle: "<texttrack>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet de définir un modèle réutilisable HTML ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<template>", estCorrecte: true },
      { libelle: "<model>", estCorrecte: false },
      { libelle: "<pattern>", estCorrecte: false },
      { libelle: "<structure>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise permet d'afficher un résumé déroulant ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<summary>", estCorrecte: true },
      { libelle: "<resume>", estCorrecte: false },
      { libelle: "<title>", estCorrecte: false },
      { libelle: "<details-title>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise crée un contenu déroulant interactif ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<details>", estCorrecte: true },
      { libelle: "<dropdown>", estCorrecte: false },
      { libelle: "<collapse>", estCorrecte: false },
      { libelle: "<toggle>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit une abréviation ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<abbr>", estCorrecte: true },
      { libelle: "<short>", estCorrecte: false },
      { libelle: "<acronym>", estCorrecte: false },
      { libelle: "<definition>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise définit un contact ou une adresse ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<address>", estCorrecte: true },
      { libelle: "<contact>", estCorrecte: false },
      { libelle: "<location>", estCorrecte: false },
      { libelle: "<place>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente une portion générique en ligne ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<span>", estCorrecte: true },
      { libelle: "<inline>", estCorrecte: false },
      { libelle: "<text>", estCorrecte: false },
      { libelle: "<line>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente un conteneur générique de bloc ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<div>", estCorrecte: true },
      { libelle: "<container>", estCorrecte: false },
      { libelle: "<block>", estCorrecte: false },
      { libelle: "<section>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise représente un texte mis en évidence ?",
    categorie: "html",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<mark>", estCorrecte: true },
      { libelle: "<highlight>", estCorrecte: false },
      { libelle: "<strong>", estCorrecte: false },
      { libelle: "<em>", estCorrecte: false },
    ],
  },

  // =====================================================
  // CSS
  // =====================================================

  {
    enonce: "Quel sélecteur cible un élément par son ID ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "#", estCorrecte: true },
      { libelle: ".", estCorrecte: false },
      { libelle: "*", estCorrecte: false },
      { libelle: "@", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel sélecteur cible un élément par sa classe ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: ".", estCorrecte: true },
      { libelle: "#", estCorrecte: false },
      { libelle: "*", estCorrecte: false },
      { libelle: "/", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété change la couleur du texte ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "color", estCorrecte: true },
      { libelle: "text-color", estCorrecte: false },
      { libelle: "font-color", estCorrecte: false },
      { libelle: "foreground", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété change la couleur de fond ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "background-color", estCorrecte: true },
      { libelle: "bg-color", estCorrecte: false },
      { libelle: "color-background", estCorrecte: false },
      { libelle: "background", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété arrondit les coins d'une bordure ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "border-radius", estCorrecte: true },
      { libelle: "corner-radius", estCorrecte: false },
      { libelle: "round-border", estCorrecte: false },
      { libelle: "border-round", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété met le texte en gras ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "font-weight", estCorrecte: true },
      { libelle: "text-weight", estCorrecte: false },
      { libelle: "font-bold", estCorrecte: false },
      { libelle: "text-style", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété met le texte en italique ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "font-style", estCorrecte: true },
      { libelle: "text-italic", estCorrecte: false },
      { libelle: "font-italic", estCorrecte: false },
      { libelle: "text-decoration", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété souligne le texte ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "text-decoration", estCorrecte: true },
      { libelle: "font-decoration", estCorrecte: false },
      { libelle: "text-underline", estCorrecte: false },
      { libelle: "underline", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété aligne le texte au centre ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "text-align: center", estCorrecte: true },
      { libelle: "align: center", estCorrecte: false },
      { libelle: "font-align: center", estCorrecte: false },
      { libelle: "center-text: true", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit la police de caractères ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "font-family", estCorrecte: true },
      { libelle: "font-type", estCorrecte: false },
      { libelle: "text-font", estCorrecte: false },
      { libelle: "typeface", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit la taille du texte ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "font-size", estCorrecte: true },
      { libelle: "text-size", estCorrecte: false },
      { libelle: "size-font", estCorrecte: false },
      { libelle: "text-scale", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété ajoute de l'espace à l'intérieur d'un élément ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "padding", estCorrecte: true },
      { libelle: "margin", estCorrecte: false },
      { libelle: "spacing", estCorrecte: false },
      { libelle: "inner-space", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété ajoute de l'espace à l'extérieur d'un élément ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "margin", estCorrecte: true },
      { libelle: "padding", estCorrecte: false },
      { libelle: "spacing", estCorrecte: false },
      { libelle: "outer-space", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle balise HTML est utilisée pour inclure un fichier CSS externe ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "<link>", estCorrecte: true },
      { libelle: "<style>", estCorrecte: false },
      { libelle: "<css>", estCorrecte: false },
      { libelle: "<script>", estCorrecte: false },
    ],
  },
  {
    enonce: "Que signifie CSS ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "Cascading Style Sheets", estCorrecte: true },
      { libelle: "Computer Style Sheets", estCorrecte: false },
      { libelle: "Creative Style Sheets", estCorrecte: false },
      { libelle: "Colorful Style Sheets", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment insérer un commentaire en CSS ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "/* commentaire */", estCorrecte: true },
      { libelle: "// commentaire //", estCorrecte: false },
      { libelle: "<!-- commentaire -->", estCorrecte: false },
      { libelle: "' commentaire", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété change le style de la puce d'une liste ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "list-style-type", estCorrecte: true },
      { libelle: "bullet-style", estCorrecte: false },
      { libelle: "list-type", estCorrecte: false },
      { libelle: "ul-style", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle valeur de 'display' permet à un élément de prendre toute la largeur disponible ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "block", estCorrecte: true },
      { libelle: "inline", estCorrecte: false },
      { libelle: "inline-block", estCorrecte: false },
      { libelle: "flex", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle valeur de 'position' est le comportement par défaut ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "static", estCorrecte: true },
      { libelle: "relative", estCorrecte: false },
      { libelle: "absolute", estCorrecte: false },
      { libelle: "fixed", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit la largeur d'un élément ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "width", estCorrecte: true },
      { libelle: "size", estCorrecte: false },
      { libelle: "length", estCorrecte: false },
      { libelle: "horizontal", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété change la couleur du curseur ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "caret-color", estCorrecte: true },
      { libelle: "cursor-color", estCorrecte: false },
      { libelle: "pointer-color", estCorrecte: false },
      { libelle: "text-caret", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit le style de la bordure ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "border-style", estCorrecte: true },
      { libelle: "border-type", estCorrecte: false },
      { libelle: "style-border", estCorrecte: false },
      { libelle: "border-format", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit l'épaisseur de la bordure ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "border-width", estCorrecte: true },
      { libelle: "border-size", estCorrecte: false },
      { libelle: "width-border", estCorrecte: false },
      { libelle: "border-thick", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété change le style du curseur ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "cursor", estCorrecte: true },
      { libelle: "pointer", estCorrecte: false },
      { libelle: "mouse-style", estCorrecte: false },
      { libelle: "cursor-style", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété masque un élément ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "display: none", estCorrecte: true },
      { libelle: "visibility: hide", estCorrecte: false },
      { libelle: "hidden: true", estCorrecte: false },
      { libelle: "opacity: hide", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété change la position d'un élément ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "position", estCorrecte: true },
      { libelle: "layout", estCorrecte: false },
      { libelle: "placement", estCorrecte: false },
      { libelle: "align", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété fixe un élément en haut de la page ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "top", estCorrecte: true },
      { libelle: "align-top", estCorrecte: false },
      { libelle: "position-top", estCorrecte: false },
      { libelle: "margin-top", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété fixe un élément à gauche ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "left", estCorrecte: true },
      { libelle: "align-left", estCorrecte: false },
      { libelle: "position-left", estCorrecte: false },
      { libelle: "margin-left", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété fixe un élément à droite ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "right", estCorrecte: true },
      { libelle: "align-right", estCorrecte: false },
      { libelle: "position-right", estCorrecte: false },
      { libelle: "margin-right", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété fixe un élément en bas ?",
    categorie: "css",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "bottom", estCorrecte: true },
      { libelle: "align-bottom", estCorrecte: false },
      { libelle: "position-bottom", estCorrecte: false },
      { libelle: "margin-bottom", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété modifie l'image d'arrière-plan ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "background-image", estCorrecte: true },
      { libelle: "img-background", estCorrecte: false },
      { libelle: "bg-image", estCorrecte: false },
      { libelle: "back-img", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment empêcher une image d'arrière-plan de se répéter ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "background-repeat: no-repeat", estCorrecte: true },
      { libelle: "repeat: none", estCorrecte: false },
      { libelle: "background: no-repeat", estCorrecte: false },
      { libelle: "img-repeat: false", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété permet d'ajuster l'image d'arrière-plan pour couvrir tout le conteneur ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "background-size: cover", estCorrecte: true },
      { libelle: "background-fit: cover", estCorrecte: false },
      { libelle: "bg-size: full", estCorrecte: false },
      { libelle: "background-size: fill", estCorrecte: false },
    ],
  },
  {
    enonce: "En Flexbox, quelle propriété aligne les éléments sur l'axe principal ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "justify-content", estCorrecte: true },
      { libelle: "align-items", estCorrecte: false },
      { libelle: "align-content", estCorrecte: false },
      { libelle: "flex-align", estCorrecte: false },
    ],
  },
  {
    enonce: "En Flexbox, quelle propriété aligne les éléments sur l'axe secondaire ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "align-items", estCorrecte: true },
      { libelle: "justify-content", estCorrecte: false },
      { libelle: "align-content", estCorrecte: false },
      { libelle: "flex-justify", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle pseudo-classe cible un lien lorsqu'il est survolé par la souris ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: ":hover", estCorrecte: true },
      { libelle: ":active", estCorrecte: false },
      { libelle: ":focus", estCorrecte: false },
      { libelle: ":visited", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle pseudo-classe cible un élément lorsqu'il est cliqué/activé ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: ":active", estCorrecte: true },
      { libelle: ":hover", estCorrecte: false },
      { libelle: ":focus", estCorrecte: false },
      { libelle: ":click", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle pseudo-classe cible un champ de formulaire sélectionné ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: ":focus", estCorrecte: true },
      { libelle: ":target", estCorrecte: false },
      { libelle: ":active", estCorrecte: false },
      { libelle: ":selected", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété permet de fusionner les bordures d'un tableau HTML ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "border-collapse: collapse", estCorrecte: true },
      { libelle: "border-merge: true", estCorrecte: false },
      { libelle: "table-layout: fixed", estCorrecte: false },
      { libelle: "border-spacing: 0", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel sélecteur cible tous les éléments <p> à l'intérieur d'un <div> ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "div p", estCorrecte: true },
      { libelle: "div + p", estCorrecte: false },
      { libelle: "div ~ p", estCorrecte: false },
      { libelle: "p > div", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel sélecteur cible uniquement les enfants directs <p> d'un <div> ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "div > p", estCorrecte: true },
      { libelle: "div p", estCorrecte: false },
      { libelle: "div + p", estCorrecte: false },
      { libelle: "div.p", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle unité CSS est relative à la taille de police de l'élément racine (html) ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "rem", estCorrecte: true },
      { libelle: "em", estCorrecte: false },
      { libelle: "vh", estCorrecte: false },
      { libelle: "px", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle unité CSS est relative à la taille de police de l'élément parent ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "em", estCorrecte: true },
      { libelle: "rem", estCorrecte: false },
      { libelle: "px", estCorrecte: false },
      { libelle: "%", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle unité CSS représente 1% de la largeur de la fenêtre (viewport) ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "vw", estCorrecte: true },
      { libelle: "vh", estCorrecte: false },
      { libelle: "vmin", estCorrecte: false },
      { libelle: "vmax", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété permet d'inclure le padding et la bordure dans la largeur totale d'un élément ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "box-sizing: border-box", estCorrecte: true },
      { libelle: "box-sizing: content-box", estCorrecte: false },
      { libelle: "width-calc: total", estCorrecte: false },
      { libelle: "display: border-box", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment sélectionner le premier enfant d'un élément parent ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: ":first-child", estCorrecte: true },
      { libelle: ":first-of-type", estCorrecte: false },
      { libelle: ":nth-child(0)", estCorrecte: false },
      { libelle: "::first", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété Flexbox permet aux éléments de passer à la ligne suivante ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "flex-wrap: wrap", estCorrecte: true },
      { libelle: "flex-flow: column", estCorrecte: false },
      { libelle: "display: block", estCorrecte: false },
      { libelle: "flex-line: break", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit l'opacité globale d'un élément et de ses enfants ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "opacity", estCorrecte: true },
      { libelle: "alpha", estCorrecte: false },
      { libelle: "visibility", estCorrecte: false },
      { libelle: "transparent", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété CSS définit une couleur d'arrière-plan en dégradé linéaire ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "background: linear-gradient()", estCorrecte: true },
      { libelle: "background-gradient: linear()", estCorrecte: false },
      { libelle: "color: gradient()", estCorrecte: false },
      { libelle: "background-color: linear()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété transforme un élément pour le rendre invisible tout en conservant son espace ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "visibility: hidden", estCorrecte: true },
      { libelle: "display: none", estCorrecte: false },
      { libelle: "opacity: 0", estCorrecte: false },
      { libelle: "hidden: true", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit le débordement d'un élément ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "overflow", estCorrecte: true },
      { libelle: "flow", estCorrecte: false },
      { libelle: "scroll-mode", estCorrecte: false },
      { libelle: "element-flow", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété ajoute une ombre au texte ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "text-shadow", estCorrecte: true },
      { libelle: "font-shadow", estCorrecte: false },
      { libelle: "shadow-text", estCorrecte: false },
      { libelle: "text-effect", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété ajoute une ombre à un élément ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "box-shadow", estCorrecte: true },
      { libelle: "shadow-box", estCorrecte: false },
      { libelle: "element-shadow", estCorrecte: false },
      { libelle: "border-shadow", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit la transparence d'une couleur ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "rgba()", estCorrecte: true },
      { libelle: "alpha()", estCorrecte: false },
      { libelle: "opacity-color()", estCorrecte: false },
      { libelle: "transparent()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété empêche le retour à la ligne ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "white-space", estCorrecte: true },
      { libelle: "line-break", estCorrecte: false },
      { libelle: "text-wrap", estCorrecte: false },
      { libelle: "no-wrap", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété transforme le texte en majuscule ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "text-transform", estCorrecte: true },
      { libelle: "font-transform", estCorrecte: false },
      { libelle: "uppercase", estCorrecte: false },
      { libelle: "text-case", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit l'espacement entre les lettres ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "letter-spacing", estCorrecte: true },
      { libelle: "text-spacing", estCorrecte: false },
      { libelle: "font-spacing", estCorrecte: false },
      { libelle: "space-letter", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit l'espacement entre les lignes ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "line-height", estCorrecte: true },
      { libelle: "text-height", estCorrecte: false },
      { libelle: "line-space", estCorrecte: false },
      { libelle: "spacing-line", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété crée une transition CSS ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "transition", estCorrecte: true },
      { libelle: "animation", estCorrecte: false },
      { libelle: "transform", estCorrecte: false },
      { libelle: "effect", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit la propriété à animer ?",
    categorie: "css",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "transition-property", estCorrecte: true },
      { libelle: "transition-target", estCorrecte: false },
      { libelle: "animation-target", estCorrecte: false },
      { libelle: "property-transition", estCorrecte: false },
    ],
  },
  {
    enonce: "En CSS Grid, quelle propriété définit le nombre et la taille des colonnes ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "grid-template-columns", estCorrecte: true },
      { libelle: "grid-columns", estCorrecte: false },
      { libelle: "grid-layout-columns", estCorrecte: false },
      { libelle: "template-columns", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel at-rule est utilisé pour définir des animations complexes en CSS ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "@keyframes", estCorrecte: true },
      { libelle: "@animation", estCorrecte: false },
      { libelle: "@transition", estCorrecte: false },
      { libelle: "@media", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété CSS permet de positionner un élément de façon absolue par rapport à la fenêtre du navigateur ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "position: fixed", estCorrecte: true },
      { libelle: "position: absolute", estCorrecte: false },
      { libelle: "position: static", estCorrecte: false },
      { libelle: "position: sticky", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle fonction permet de calculer dynamiquement une valeur CSS (ex: 100% - 50px) ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "calc()", estCorrecte: true },
      { libelle: "math()", estCorrecte: false },
      { libelle: "compute()", estCorrecte: false },
      { libelle: "eval()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel pseudo-élément permet d'insérer du contenu avant le contenu d'un élément ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "::before", estCorrecte: true },
      { libelle: "::start", estCorrecte: false },
      { libelle: "::first", estCorrecte: false },
      { libelle: "::prepend", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel pseudo-élément permet de modifier le style de la première lettre d'un bloc de texte ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "::first-letter", estCorrecte: true },
      { libelle: "::letter(1)", estCorrecte: false },
      { libelle: "::start-letter", estCorrecte: false },
      { libelle: "::initial", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle syntaxe Media Query cible les écrans ayant une largeur maximale de 768px ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "@media (max-width: 768px)", estCorrecte: true },
      { libelle: "@media (min-width: 768px)", estCorrecte: false },
      { libelle: "@media screen <= 768px", estCorrecte: false },
      { libelle: "@responsive (max: 768px)", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit la direction de l'axe principal en Flexbox ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "flex-direction", estCorrecte: true },
      { libelle: "flex-flow", estCorrecte: false },
      { libelle: "flex-axis", estCorrecte: false },
      { libelle: "flex-orientation", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel sélecteur CSS cible les éléments de type 'input' ayant l'attribut type='text' ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "input[type='text']", estCorrecte: true },
      { libelle: "input:text", estCorrecte: false },
      { libelle: "input(text)", estCorrecte: false },
      { libelle: "input.type-text", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle valeur de 'position' permet à un élément d'être 'relatif' jusqu'à un certain point de défilement, puis 'fixe' ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "sticky", estCorrecte: true },
      { libelle: "fixed", estCorrecte: false },
      { libelle: "relative", estCorrecte: false },
      { libelle: "absolute", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété permet d'isoler le défilement d'un élément (overscroll) pour qu'il n'affecte pas le parent ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "overscroll-behavior", estCorrecte: true },
      { libelle: "scroll-snap", estCorrecte: false },
      { libelle: "overflow-anchor", estCorrecte: false },
      { libelle: "scroll-behavior", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle fonction CSS est utilisée pour faire pivoter un élément ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "rotate()", estCorrecte: true },
      { libelle: "turn()", estCorrecte: false },
      { libelle: "spin()", estCorrecte: false },
      { libelle: "angle()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété CSS définit le comportement de défilement fluide lors du clic sur des ancres ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "scroll-behavior: smooth", estCorrecte: true },
      { libelle: "transition: scroll", estCorrecte: false },
      { libelle: "scroll-mode: smooth", estCorrecte: false },
      { libelle: "animation: scroll", estCorrecte: false },
    ],
  },
  {
    enonce: "En CSS Grid, comment faire en sorte qu'un élément occupe deux colonnes ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "grid-column: span 2", estCorrecte: true },
      { libelle: "grid-width: 2", estCorrecte: false },
      { libelle: "colspan: 2", estCorrecte: false },
      { libelle: "grid-span: 2", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel sélecteur pseudo-classe sélectionne l'élément uniquement s'il n'a pas d'enfants ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: ":empty", estCorrecte: true },
      { libelle: ":blank", estCorrecte: false },
      { libelle: ":no-child", estCorrecte: false },
      { libelle: ":void", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment désactiver la sélection de texte par l'utilisateur sur un élément ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "user-select: none", estCorrecte: true },
      { libelle: "text-select: false", estCorrecte: false },
      { libelle: "pointer-events: none", estCorrecte: false },
      { libelle: "selection: none", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle fonction de transformation CSS permet de déplacer un élément sur l'axe X et Y ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "translate()", estCorrecte: true },
      { libelle: "move()", estCorrecte: false },
      { libelle: "position()", estCorrecte: false },
      { libelle: "shift()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété CSS empêche les clics de souris sur un élément ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "pointer-events: none", estCorrecte: true },
      { libelle: "cursor: none", estCorrecte: false },
      { libelle: "click-events: false", estCorrecte: false },
      { libelle: "mouse-action: none", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle pseudo-classe permet de cibler le Nième enfant pair d'un parent ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: ":nth-child(even)", estCorrecte: true },
      { libelle: ":nth-child(2n)", estCorrecte: false },
      { libelle: ":even-child", estCorrecte: false },
      { libelle: ":child(even)", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété permet de changer la façon dont le curseur apparaît lorsqu'il survole un élément (ex: main cliquable) ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "cursor: pointer", estCorrecte: true },
      { libelle: "mouse: pointer", estCorrecte: false },
      { libelle: "cursor-style: hand", estCorrecte: false },
      { libelle: "hover-icon: pointer", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle fonction incline un élément ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "skew()", estCorrecte: true },
      { libelle: "tilt()", estCorrecte: false },
      { libelle: "angle()", estCorrecte: false },
      { libelle: "bend()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété combine flex-grow, flex-shrink et flex-basis ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "flex", estCorrecte: true },
      { libelle: "flex-all", estCorrecte: false },
      { libelle: "flex-group", estCorrecte: false },
      { libelle: "flex-main", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit la zone d'une grille ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "grid-area", estCorrecte: true },
      { libelle: "grid-zone", estCorrecte: false },
      { libelle: "area-grid", estCorrecte: false },
      { libelle: "grid-layout-area", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit l'espace entre les colonnes ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "column-gap", estCorrecte: true },
      { libelle: "grid-gap-column", estCorrecte: false },
      { libelle: "gap-column", estCorrecte: false },
      { libelle: "space-column", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété définit l'espace entre les lignes ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "row-gap", estCorrecte: true },
      { libelle: "grid-gap-row", estCorrecte: false },
      { libelle: "gap-row", estCorrecte: false },
      { libelle: "space-row", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété permet d'utiliser une variable CSS ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "var()", estCorrecte: true },
      { libelle: "variable()", estCorrecte: false },
      { libelle: "css-var()", estCorrecte: false },
      { libelle: "value()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle syntaxe déclare une variable CSS ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "--ma-couleur", estCorrecte: true },
      { libelle: "$couleur", estCorrecte: false },
      { libelle: "@color", estCorrecte: false },
      { libelle: "#variable", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété permet d'utiliser un filtre ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "filter", estCorrecte: true },
      { libelle: "image-filter", estCorrecte: false },
      { libelle: "graphic-filter", estCorrecte: false },
      { libelle: "effect-filter", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle fonction CSS floute un élément ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "blur()", estCorrecte: true },
      { libelle: "fuzzy()", estCorrecte: false },
      { libelle: "soft()", estCorrecte: false },
      { libelle: "fog()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété contrôle l'ordre d'empilement ?",
    categorie: "css",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "z-index", estCorrecte: true },
      { libelle: "layer", estCorrecte: false },
      { libelle: "stack-order", estCorrecte: false },
      { libelle: "depth", estCorrecte: false },
    ],
  },

  // =====================================================
  // JAVASCRIPT
  // =====================================================

  {
    enonce: "Comment déclare-t-on une constante ?",
    categorie: "javascript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "const", estCorrecte: true },
      { libelle: "let", estCorrecte: false },
      { libelle: "var", estCorrecte: false },
      { libelle: "constant", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle méthode convertit un objet en JSON ?",
    categorie: "javascript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "JSON.stringify()", estCorrecte: true },
      { libelle: "JSON.parse()", estCorrecte: false },
      { libelle: "JSON.object()", estCorrecte: false },
      { libelle: "JSON.convert()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle méthode sélectionne un élément par ID ?",
    categorie: "javascript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "document.getElementById()", estCorrecte: true },
      { libelle: "querySelectorAll()", estCorrecte: false },
      { libelle: "getElement()", estCorrecte: false },
      { libelle: "document.id()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel mot-clé crée une fonction fléchée ?",
    categorie: "javascript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "=>", estCorrecte: true },
      { libelle: "function", estCorrecte: false },
      { libelle: "arrow", estCorrecte: false },
      { libelle: "->", estCorrecte: false },
    ],
  },

  // =====================================================
  // TYPESCRIPT
  // =====================================================

  {
    enonce: "Quel mot-clé permet de définir un alias de type ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "type", estCorrecte: true },
      { libelle: "alias", estCorrecte: false },
      { libelle: "interface", estCorrecte: false },
      { libelle: "declare", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment déclare-t-on un tableau de nombres ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "number[]", estCorrecte: true },
      { libelle: "Array<number[]>", estCorrecte: false },
      { libelle: "[number]", estCorrecte: false },
      { libelle: "list<number>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type est utilisé pour une fonction qui ne retourne rien ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "void", estCorrecte: true },
      { libelle: "never", estCorrecte: false },
      { libelle: "null", estCorrecte: false },
      { libelle: "undefined", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type accepte n'importe quelle valeur sans vérification ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "any", estCorrecte: true },
      { libelle: "unknown", estCorrecte: false },
      { libelle: "object", estCorrecte: false },
      { libelle: "all", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment définit-on un Tuple de deux éléments (string, number) ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "[string, number]", estCorrecte: true },
      { libelle: "{string, number}", estCorrecte: false },
      { libelle: "Pair<string, number>", estCorrecte: false },
      { libelle: "(string | number)[]", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel mot-clé permet à une classe d'utiliser une interface ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "implements", estCorrecte: true },
      { libelle: "extends", estCorrecte: false },
      { libelle: "using", estCorrecte: false },
      { libelle: "apply", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type représente une valeur qui n'arrivera jamais ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "never", estCorrecte: true },
      { libelle: "void", estCorrecte: false },
      { libelle: "null", estCorrecte: false },
      { libelle: "unknown", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment définit-on une intersection de types ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "TypeA & TypeB", estCorrecte: true },
      { libelle: "TypeA | TypeB", estCorrecte: false },
      { libelle: "TypeA + TypeB", estCorrecte: false },
      { libelle: "TypeA && TypeB", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel modificateur rend une propriété accessible uniquement dans la classe ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "private", estCorrecte: true },
      { libelle: "protected", estCorrecte: false },
      { libelle: "hidden", estCorrecte: false },
      { libelle: "readonly", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel modificateur permet l'accès dans la classe et ses sous-classes ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "protected", estCorrecte: true },
      { libelle: "private", estCorrecte: false },
      { libelle: "internal", estCorrecte: false },
      { libelle: "public", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment empêcher la modification d'une propriété après initialisation ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "readonly", estCorrecte: true },
      { libelle: "const", estCorrecte: false },
      { libelle: "static", estCorrecte: false },
      { libelle: "final", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle commande compile un fichier TypeScript en JavaScript ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "tsc", estCorrecte: true },
      { libelle: "ts-node", estCorrecte: false },
      { libelle: "npm compile", estCorrecte: false },
      { libelle: "typescript-build", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel est le type par défaut d'une variable non initialisée sans type explicite ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "any", estCorrecte: true },
      { libelle: "undefined", estCorrecte: false },
      { libelle: "unknown", estCorrecte: false },
      { libelle: "null", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment forcer un type (Type Assertion) ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "variable as string", estCorrecte: true },
      { libelle: "cast<string>(variable)", estCorrecte: false },
      { libelle: "variable: string", estCorrecte: false },
      { libelle: "convert(variable, string)", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment définit-on un paramètre avec une valeur par défaut ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "nom: string = 'Inconnu'", estCorrecte: true },
      { libelle: "nom: string default 'Inconnu'", estCorrecte: false },
      { libelle: "nom?: string = 'Inconnu'", estCorrecte: false },
      { libelle: "default nom: string = 'Inconnu'", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel fichier configure les options du compilateur TypeScript ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "tsconfig.json", estCorrecte: true },
      { libelle: "package.json", estCorrecte: false },
      { libelle: "tsconfig.xml", estCorrecte: false },
      { libelle: "typescript.config", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel mot-clé définit une énumération ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "enum", estCorrecte: true },
      { libelle: "list", estCorrecte: false },
      { libelle: "union", estCorrecte: false },
      { libelle: "const list", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type est plus sûr que 'any' car il oblige à vérifier le type avant usage ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "unknown", estCorrecte: true },
      { libelle: "never", estCorrecte: false },
      { libelle: "void", estCorrecte: false },
      { libelle: "object", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment déclare-t-on une fonction fléchée typée ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "(a: number) => number", estCorrecte: true },
      { libelle: "function(a: number): number", estCorrecte: false },
      { libelle: "(a: number): number", estCorrecte: false },
      { libelle: "number => number", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel opérateur vérifie si une propriété appartient à un objet pour le Type Guard ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "in", estCorrecte: true },
      { libelle: "instanceof", estCorrecte: false },
      { libelle: "typeof", estCorrecte: false },
      { libelle: "has", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment appelle-t-on la capacité de TypeScript à deviner le type d'une variable ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "Type Inference", estCorrecte: true },
      { libelle: "Type Casting", estCorrecte: false },
      { libelle: "Type Guard", estCorrecte: false },
      { libelle: "Duck Typing", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle syntaxe utilise-t-on pour les Generics ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<T>", estCorrecte: true },
      { libelle: "[T]", estCorrecte: false },
      { libelle: "{T}", estCorrecte: false },
      { libelle: "(T)", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel utilitaire de type rend toutes les propriétés d'une interface optionnelles ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Partial<T>", estCorrecte: true },
      { libelle: "Omit<T>", estCorrecte: false },
      { libelle: "Pick<T>", estCorrecte: false },
      { libelle: "Readonly<T>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel utilitaire de type rend toutes les propriétés d'une interface obligatoires ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Required<T>", estCorrecte: true },
      { libelle: "Partial<T>", estCorrecte: false },
      { libelle: "Mandatory<T>", estCorrecte: false },
      { libelle: "Full<T>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel utilitaire permet de créer un type en retirant certaines clés d'une interface ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Omit<T, K>", estCorrecte: true },
      { libelle: "Exclude<T, K>", estCorrecte: false },
      { libelle: "Pick<T, K>", estCorrecte: false },
      { libelle: "Remove<T, K>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel utilitaire permet de créer un type en ne gardant que certaines clés d'une interface ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Pick<T, K>", estCorrecte: true },
      { libelle: "Select<T, K>", estCorrecte: false },
      { libelle: "Extract<T, K>", estCorrecte: false },
      { libelle: "Omit<T, K>", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment définit-on une contrainte sur un paramètre générique ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "<T extends K>", estCorrecte: true },
      { libelle: "<T implements K>", estCorrecte: false },
      { libelle: "<T : K>", estCorrecte: false },
      { libelle: "<T typeof K>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel opérateur permet d'obtenir les clés d'un type sous forme d'union de strings ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "keyof", estCorrecte: true },
      { libelle: "typeof", estCorrecte: false },
      { libelle: "instanceof", estCorrecte: false },
      { libelle: "keys", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment déclare-t-on un membre statique dans une classe ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "static", estCorrecte: true },
      { libelle: "const", estCorrecte: false },
      { libelle: "fixed", estCorrecte: false },
      { libelle: "final", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel mot-clé permet d'hériter d'une autre classe ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "extends", estCorrecte: true },
      { libelle: "implements", estCorrecte: false },
      { libelle: "inherits", estCorrecte: false },
      { libelle: "prototype", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type représente une paire clé/valeur dynamique ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "{ [key: string]: any }", estCorrecte: true },
      { libelle: "Map<string, any>", estCorrecte: false },
      { libelle: "Record<string>", estCorrecte: false },
      { libelle: "Dictionary<any>", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment définit-on un type qui peut être soit une string, soit null ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "string | null", estCorrecte: true },
      { libelle: "string?", estCorrecte: false },
      { libelle: "nullable string", estCorrecte: false },
      { libelle: "Optional<string>", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type utilitaire permet de définir les clés et le type de valeur d'un objet ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Record<K, T>", estCorrecte: true },
      { libelle: "Map<K, T>", estCorrecte: false },
      { libelle: "Dictionary<K, T>", estCorrecte: false },
      { libelle: "Collection<K, T>", estCorrecte: false },
    ],
  },
  {
    enonce: "Que signifie le point d'exclamation après une variable (ex: x!) ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Non-null assertion operator", estCorrecte: true },
      { libelle: "Optional chaining", estCorrecte: false },
      { libelle: "Logical NOT", estCorrecte: false },
      { libelle: "Variable declaration", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel opérateur permet d'accéder à une propriété sans erreur si le parent est null/undefined ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "?.", estCorrecte: true },
      { libelle: "??", estCorrecte: false },
      { libelle: "!!", estCorrecte: false },
      { libelle: "?:", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel opérateur retourne la valeur de droite si celle de gauche est null ou undefined ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "??", estCorrecte: true },
      { libelle: "?.", estCorrecte: false },
      { libelle: "||", estCorrecte: false },
      { libelle: "&&", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment définit-on une classe abstraite ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "abstract class", estCorrecte: true },
      { libelle: "interface class", estCorrecte: false },
      { libelle: "virtual class", estCorrecte: false },
      { libelle: "static class", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type de décorateur n'existe pas en TypeScript ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Variable Decorator", estCorrecte: true },
      { libelle: "Class Decorator", estCorrecte: false },
      { libelle: "Method Decorator", estCorrecte: false },
      { libelle: "Property Decorator", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment s'appelle l'extension de fichier pour les fichiers de définition de types ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: ".d.ts", estCorrecte: true },
      { libelle: ".t.ds", estCorrecte: false },
      { libelle: ".types.ts", estCorrecte: false },
      { libelle: ".def.ts", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel mot-clé est utilisé pour importer un type uniquement (depuis TS 3.8) ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "import type", estCorrecte: true },
      { libelle: "import { type }", estCorrecte: false },
      { libelle: "using type", estCorrecte: false },
      { libelle: "require type", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type est assigné à une constante de chaîne de caractères (ex: const x = 'hello') ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "Literal Type ('hello')", estCorrecte: true },
      { libelle: "string", estCorrecte: false },
      { libelle: "any", estCorrecte: false },
      { libelle: "const string", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle option de tsconfig empêche l'usage de 'any' implicite ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "noImplicitAny", estCorrecte: true },
      { libelle: "strictAny", estCorrecte: false },
      { libelle: "denyAny", estCorrecte: false },
      { libelle: "noAny", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment extraire le type des éléments d'un tableau ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "T[number]", estCorrecte: true },
      { libelle: "T.element", estCorrecte: false },
      { libelle: "ArrayItem<T>", estCorrecte: false },
      { libelle: "typeof T[]", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment définit-on une interface qui hérite d'une autre ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "interface A extends B", estCorrecte: true },
      { libelle: "interface A implements B", estCorrecte: false },
      { libelle: "interface A : B", estCorrecte: false },
      { libelle: "interface A & B", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle propriété de tsconfig définit la version de JavaScript générée ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "target", estCorrecte: true },
      { libelle: "module", estCorrecte: false },
      { libelle: "lib", estCorrecte: false },
      { libelle: "output", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type utilitaire permet d'extraire le type de retour d'une fonction ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "ReturnType<T>", estCorrecte: true },
      { libelle: "GetReturn<T>", estCorrecte: false },
      { libelle: "OutputOf<T>", estCorrecte: false },
      { libelle: "FunctionReturn<T>", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment déclarer une variable globale dans un fichier .d.ts ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "declare var", estCorrecte: true },
      { libelle: "global var", estCorrecte: false },
      { libelle: "export global", estCorrecte: false },
      { libelle: "window.var", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle interface définit un objet avec des propriétés de n'importe quel nom ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Index Signature", estCorrecte: true },
      { libelle: "Dynamic Interface", estCorrecte: false },
      { libelle: "Open Object", estCorrecte: false },
      { libelle: "Any Key", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel mot-clé est nécessaire pour utiliser 'this' dans un constructeur de sous-classe ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "super()", estCorrecte: true },
      { libelle: "parent()", estCorrecte: false },
      { libelle: "this.init()", estCorrecte: false },
      { libelle: "base()", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel utilitaire de type exclut 'null' et 'undefined' d'un type ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "NonNullable<T>", estCorrecte: true },
      { libelle: "NotNull<T>", estCorrecte: false },
      { libelle: "Required<T>", estCorrecte: false },
      { libelle: "Defined<T>", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment typer une promesse qui renvoie une string ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "Promise<string>", estCorrecte: true },
      { libelle: "Async<string>", estCorrecte: false },
      { libelle: "string.promise", estCorrecte: false },
      { libelle: "Promise(string)", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel mot-clé permet de fusionner plusieurs déclarations d'interface ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Declaration Merging (automatique)", estCorrecte: true },
      { libelle: "merge", estCorrecte: false },
      { libelle: "combine", estCorrecte: false },
      { libelle: "concat", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment déclare-t-on un paramètre 'Reste' (rest parameter) typé ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "...args: number[]", estCorrecte: true },
      { libelle: "args: ...number[]", estCorrecte: false },
      { libelle: "[]args: number", estCorrecte: false },
      { libelle: "rest args: number", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel modificateur est utilisé pour créer des accesseurs ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "get / set", estCorrecte: true },
      { libelle: "read / write", estCorrecte: false },
      { libelle: "accessor", estCorrecte: false },
      { libelle: "val / var", estCorrecte: false },
    ],
  },
  {
    enonce: "Quelle est la valeur de départ du premier élément d'un enum par défaut ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "0", estCorrecte: true },
      { libelle: "1", estCorrecte: false },
      { libelle: "null", estCorrecte: false },
      { libelle: "undefined", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel type permet de définir un objet dont on ne connaît pas la structure à l'avance ?",
    categorie: "typescript",
    difficulte: 2,
    pointsValeur: 15,
    choix: [
      { libelle: "object", estCorrecte: true },
      { libelle: "AnyObject", estCorrecte: false },
      { libelle: "Struct", estCorrecte: false },
      { libelle: "dynamic", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel utilitaire de type permet d'obtenir les types des paramètres d'une fonction ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Parameters<T>", estCorrecte: true },
      { libelle: "ArgsOf<T>", estCorrecte: false },
      { libelle: "InputTypes<T>", estCorrecte: false },
      { libelle: "ConstructorParameters<T>", estCorrecte: false },
    ],
  },
  {
    enonce: "Que fait l'option 'strictNullChecks' ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Empêche d'assigner null aux types de base", estCorrecte: true },
      { libelle: "Autorise null partout", estCorrecte: false },
      { libelle: "Supprime les valeurs nulles", estCorrecte: false },
      { libelle: "Vérifie si une variable est null à l'exécution", estCorrecte: false },
    ],
  },
  {
    enonce: "Quel mot-clé est utilisé pour les modules en TypeScript ?",
    categorie: "typescript",
    difficulte: 1,
    pointsValeur: 10,
    choix: [
      { libelle: "export", estCorrecte: true },
      { libelle: "public", estCorrecte: false },
      { libelle: "expose", estCorrecte: false },
      { libelle: "module.out", estCorrecte: false },
    ],
  },
  {
    enonce: "Comment appelle-t-on le fait de définir plusieurs signatures pour une même fonction ?",
    categorie: "typescript",
    difficulte: 3,
    pointsValeur: 20,
    choix: [
      { libelle: "Function Overloading", estCorrecte: true },
      { libelle: "Function Redefinition", estCorrecte: false },
      { libelle: "Multi-typing", estCorrecte: false },
      { libelle: "Shadowing", estCorrecte: false },
    ],
  },
];

async function seed() {
  console.log("Début du remplissage...");

  try {
    for (const q of questionsData) {
      const question = await prisma.question.create({
        data: {
          enonce: q.enonce,
          categorie: q.categorie,
          difficulte: q.difficulte,
          pointsValeur: q.pointsValeur,
        },
      });

      await prisma.reponse.createMany({
        data: q.choix.map((c) => ({
          libelle: c.libelle,
          estCorrecte: c.estCorrecte,
          questionId: question.id,
        })),
      });
    }

    console.log("Base remplie avec succès !");
  } catch (error) {
    console.error(error);
  } finally {
    await prisma.$disconnect();
    process.exit();
  }
}

seed();